"""create webhook delivery attempts

Revision ID: 10f4dd620e97
Revises: df51b920cf81
Create Date: 2026-07-23 13:43:49.966079

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "10f4dd620e97"
down_revision: str | Sequence[str] | None = "df51b920cf81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_delivery_attempts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("response_status_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('succeeded', 'failed')", name="ck_webhook_delivery_attempts_outcome"
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name="ck_webhook_delivery_attempts_attempt_number_positive"
        ),
        sa.CheckConstraint(
            "duration_ms >= 0", name="ck_webhook_delivery_attempts_duration_ms_non_negative"
        ),
        sa.CheckConstraint(
            "response_status_code IS NULL OR response_status_code BETWEEN 100 AND 599",
            name="ck_webhook_delivery_attempts_response_status_code",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["webhook_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id",
            "attempt_number",
            name="uq_webhook_delivery_attempts_event_id_attempt_number",
        ),
    )
    op.create_index(
        "ix_webhook_delivery_attempts_event_id",
        "webhook_delivery_attempts",
        ["event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_webhook_delivery_attempts_event_id",
        table_name="webhook_delivery_attempts",
    )
    op.drop_table("webhook_delivery_attempts")
    # ### end Alembic commands ###
